# Generated by Django 4.1.6 on 2023-03-22 18:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
